# The name of the database used to store
storage:
  database: "Cosmetics"
  collection: "profiles"

# If this server is considered a game-mode server.
# If true, cosmetics won't modify player data without certain checks in place.
game-server: true